### ISSUE TITLE
InternVid dataset

### ISSUE THREAD

**Issue by wjchaoGit** [OpenGVLab/InternVideo#60]
Thank you very much for providing such a large-scale, high-quality dataset. I would like to ask:
1. Could you provide download link for the processed video clips? I saw a processed video clips download link at https://opendatalab.com/shepshep/InternVid, which points to https://openxlab.org.cn/datasets/yinanhe/InternVid-10M-FLT, but the webpage currently shows 404 not found.
2. Do you have any plans to provide ViCLIP features extracted from the InternVid dataset?

**Comment by yinanhe** [comment]
Hi, thank you for your attention to our work. Due to copyright reasons, we are unable to directly provide you with the download link for the video in the near future. You may consider using tools such as yt-dlp or youtube-dl for downloading. We will consider releasing the ViCLIP features video features soon.
