### ISSUE TITLE
Release of video-language contrastive learning code?

### ISSUE THREAD

**Issue by CountingClouds** [OpenGVLab/InternVideo#7]
Thank you everyone on the team for all of your excellent work and releasing it under a permissive license to the ML community!!

Q: I am wondering about the **multi-modal video-language contrastive learning** components of the code. Is there a planned date for its release?  It would be great to start working with it in time for ICCV coming up soon

**Comment by CountingClouds** [comment]
Similarly, it would also be great to get the captioning training code

**Comment by CountingClouds** [comment]
Thank for releasing much of the MultiModalitiesPretraining code!

**Comment by CountingClouds** [comment]
I've noticed in model.py that it attempts to load 'vit_2plus1d_dw_bias_b16' from clip.util.clip_vit_only_global.py, which only has defined functions like 'vit_only_global_b16' (ie vit only) but not the modified uniformer versions.  Am I missing something or is this missing from the repo?

Also - Would be great to get the multimodal-contrastive-captioning training code.

**Comment by liyz15** [comment]
Thank you for trying out InternVideo!

'vit_only_global_b16' is a modified uniformer version, see the [Transformer module](https://github.com/OpenGVLab/InternVideo/blob/27333740b50cdf6317f1313dd4cc6a6fbc11fe8e/Pretrain/Multi-Modalities-Pretraining/InternVideo/clip_utils/utils/clip_vit_only_global.py#L152) in the file.

The training code is still WIP. You can try the code in downstream with config

https://github.com/OpenGVLab/InternVideo/blob/27333740b50cdf6317f1313dd4cc6a6fbc11fe8e/Downstream/multi-modalities-downstream/CoTrain/config.py#L539

but it's not guaranteed to work as expected since we modified a lot when cleaning code.
