### ISSUE TITLE
will 13b or other bigger model be released for videochat2?

### ISSUE THREAD

**Issue by dragen1860** [OpenGVLab/InternVideo#74]
hi, thanks for releasing the 7b version of videochat2.  I wonder would you like to kinndly share the larger version models?

**Comment by yinanhe** [comment]
Hi! Thank you for your interest in our work. Currently, we don't have a plan to release the 13B pretrained models, since the performances are similar in our experiments. And 13B requires more GPU sources for training. Recently, we plan to adapt VideoChat with other popular LLM, and we will upload the results if it's better.

**Comment by dragen1860** [comment]
sounds good. very exicted to see more emergent abilities for other larger llm.
